Adaptive kernel Kalman filter (AKKF)
dstl/Stone-Soup pull request #1014
Opened 2024-05-13 07:38 UTC by jswright-dstl

This PR adds the Adaptive kernel Kalman filter (AKKF) [1]. The implementation includes the following:
- Kernel classes
  - `QuadraticKernel` 
  - `QuarticKernel`
  - `GaussianKernel`
- `AdaptiveKernelKalmanPredictor`
- `AdaptiveKernelKalmanUpdater`
- `KernelParticleState`
- AKKF Tutorial

The above implementations are described in [2]. 

[1] M. Sun, M. E. Davies, I. Proudler and J. R. Hopgood, "Adaptive Kernel Kalman Filter," 2021 Sensor Signal Processing for Defence Conference (SSPD), Edinburgh, United Kingdom, 2021, pp. 1-5, doi: 10.1109/SSPD51364.2021.9541455.
[2] J. S. Wright, J. R. Hopgood, M. E. Davies, I. K. Proudler and M. Sun, "Implementation of Adaptive Kernel Kalman Filter in Stone Soup," 2023 Sensor Signal Processing for Defence Conference (SSPD), Edinburgh, United Kingdom, 2023, pp. 1-5, doi: 10.1109/SSPD57945.2023.10256739.

2024-05-16 13:26 UTC, sdhiscocks commented on stonesoup/updater/kernel.py
> +            "Default is 2")
Default doesn't match doc.

2024-05-16 13:26 UTC, sdhiscocks commented on stonesoup/updater/kernel.py
> +        doc="Kernel")
Document default when `None`.

2024-05-16 13:38 UTC, sdhiscocks commented on stonesoup/types/state.py
> +        return self.state_vector @ self.kernel_covar @ self.state_vector.T
```suggestion
    @clearable_cached_property('state_vector', 'weight')
    def mean(self):
        return self.state_vector @ self.weight

    @clearable_cached_property('state_vector', 'kernel_covar')
    def covar(self):
        return self.state_vector @ self.kernel_covar @ self.state_vector.T
```

2024-05-16 13:39 UTC, sdhiscocks commented on stonesoup/types/state.py
> +        return self.state_vector @ self.kernel_covar @ self.state_vector.T
No weight for covar?

2024-05-16 13:41 UTC, sdhiscocks commented on docs/tutorials/filters/AKKF.py
> +plotter.fig
Adding the comment below should use last image for gallery thumbnail, which I think is better.

```suggestion
# %%

# sphinx_gallery_thumbnail_number = -1

plotter.plot_tracks(track, [0, 2], track_label='AKKF - quadratic', color='royalblue', particle=True)
plotter.fig
```

2024-05-17 10:58 UTC, jswright-dstl commented on stonesoup/kernel.py
> +
Removed.

2024-05-17 10:58 UTC, jswright-dstl commented on stonesoup/kernel.py
> +                self.ialpha + self.c) ** 4
Changed.

2024-05-17 10:58 UTC, jswright-dstl commented on stonesoup/kernel.py
> +                state_vector2 = state2
Moved to private method in base Kernel class.

2024-05-17 10:59 UTC, jswright-dstl commented on stonesoup/kernel.py
> +            np.sqrt(2 * np.pi * self.variance))
Changed.

2024-05-17 10:59 UTC, jswright-dstl commented on stonesoup/predictor/kernel.py
> +import numpy as np
Added.

2024-05-17 11:03 UTC, jswright-dstl commented on stonesoup/predictor/kernel.py
> +            self.kernel = QuadraticKernel()
Removed.

2024-05-17 11:03 UTC, jswright-dstl commented on stonesoup/predictor/kernel.py
> +                proposal = copy.deepcopy(prior)
Changed to copy.

2024-05-17 11:04 UTC, jswright-dstl commented on stonesoup/predictor/kernel.py
> +                len(prior))) @ k_tilde_tilde - np.identity(len(prior))).T / len(prior)
Happy with the tidy up of the equations. Changed.

2024-05-17 11:09 UTC, jswright-dstl commented on stonesoup/updater/kernel.py
> +            state_vector=new_state_vector)
Added `measurement_noise`.

2024-05-17 11:11 UTC, jswright-dstl commented on stonesoup/updater/kernel.py
> +            predicted_state.kernel_covar - Q_AKKF @ G_yy @ predicted_state.kernel_covar
Changed.

2024-05-17 13:30 UTC, jswright-dstl commented on stonesoup/predictor/kernel.py
> +        doc="Kernel")
Added.

2024-05-17 13:31 UTC, jswright-dstl commented on stonesoup/predictor/kernel.py
> +    def predict(self, prior, proposal=None, timestamp=None, **kwargs):
Changed.

2024-05-17 13:31 UTC, jswright-dstl commented on stonesoup/updater/kernel.py
> +            "Default is 2")
Changed doc.

2024-05-17 13:31 UTC, jswright-dstl commented on stonesoup/updater/kernel.py
> +        doc="Kernel")
Added.

2024-05-17 13:31 UTC, jswright-dstl commented on stonesoup/kernel.py
> +                self.ialpha + self.c) ** 2
Changed.

2024-06-27 07:04 UTC, sdhiscocks requested changes
Minor doc suggestions, and change to which variable being used to reset caching.

Also found issue with weights of state being inconsistent, so proposed below to fix that.

```diff
diff --git a/stonesoup/predictor/kernel.py b/stonesoup/predictor/kernel.py
index e329809d..cdcd1361 100644
--- a/stonesoup/predictor/kernel.py
+++ b/stonesoup/predictor/kernel.py
@@ -76,7 +76,7 @@ class AdaptiveKernelKalmanPredictor(KalmanPredictor):
         prediction_covariance = kernel_t @ prior.kernel_covar @ kernel_t.T + v
         return Prediction.from_state(prior,
                                      state_vector=new_state_vector,
-                                     weight=np.squeeze(prediction_weights),
+                                     weight=prediction_weights,
                                      kernel_covar=prediction_covariance,
                                      timestamp=timestamp,
                                      transition_model=self.transition_model)
diff --git a/stonesoup/types/state.py b/stonesoup/types/state.py
index f1965f1b..ea116e7f 100644
--- a/stonesoup/types/state.py
+++ b/stonesoup/types/state.py
@@ -945,7 +945,7 @@ class KernelParticleState(State):
 
     @clearable_cached_property('state_vector', 'weight')
     def mean(self):
-        return self.state_vector @ self.weight
+        return self.state_vector @ self.weight[:, np.newaxis]
 
     @clearable_cached_property('state_vector', 'weight')
     def covar(self):
diff --git a/stonesoup/types/tests/test_state.py b/stonesoup/types/tests/test_state.py
index 3fd80f69..eba966ce 100644
--- a/stonesoup/types/tests/test_state.py
+++ b/stonesoup/types/tests/test_state.py
@@ -863,5 +863,5 @@ def test_kernel_particle_state():
     assert np.array_equal(prior.kernel_covar, prior_w_kernel_covar.kernel_covar)
     assert number_particles == len(prior)
     assert 4 == prior.ndim
-    assert np.array_equal(state_vector @ weights, prior.mean)
+    assert np.array_equal(state_vector @ weights[:, np.newaxis], prior.mean)
     assert np.array_equal(state_vector @ np.diag(weights) @ state_vector.T, prior.covar)
diff --git a/stonesoup/updater/kernel.py b/stonesoup/updater/kernel.py
index 9860675a..e9998377 100644
--- a/stonesoup/updater/kernel.py
+++ b/stonesoup/updater/kernel.py
@@ -86,14 +86,13 @@ class AdaptiveKernelKalmanUpdater(Updater):
             predicted_state.kernel_covar \
             @ np.linalg.pinv(G_yy @ predicted_state.kernel_covar
                              + self.lambda_updater * np.identity(len(predicted_state)))
-        updated_weights = \
-            np.atleast_2d(predicted_state.weight).T \
-            + Q_AKKF @ (g_y - np.atleast_2d(G_yy @ predicted_state.weight).T)
+        weights = predicted_state.weight[:, np.newaxis]
+        updated_weights = (weights + Q_AKKF@(g_y - G_yy@weights)).ravel()
         updated_covariance = \
             predicted_state.kernel_covar - Q_AKKF @ G_yy @ predicted_state.kernel_covar
 
         # Proposal Calculation
-        pred_mean = predicted_state.state_vector @ np.squeeze(updated_weights)
+        pred_mean = predicted_state.state_vector @ updated_weights
         pred_covar = np.diag(np.diag(
             predicted_state.state_vector @ updated_covariance @ predicted_state.state_vector.T))
 
diff --git a/stonesoup/updater/tests/test_kernel.py b/stonesoup/updater/tests/test_kernel.py
index ceea0c64..06c671f7 100644
--- a/stonesoup/updater/tests/test_kernel.py
+++ b/stonesoup/updater/tests/test_kernel.py
@@ -108,7 +108,7 @@ def test_kernel_updater(kernel, measurement_model, c, ialpha):
     assert update.hypothesis.measurement.timestamp == gt_state.timestamp
     assert np.allclose(update.state_vector, prediction.state_vector)
     assert np.allclose(update.proposal, StateVectors(new_state_vector.T), atol=1e0)
-    assert np.allclose(update.weight, updated_weights)
+    assert np.allclose(update.weight, updated_weights.ravel())
     assert np.allclose(update.kernel_covar, updated_covariance)
 
 
```

2024-07-04 06:46 UTC, sdhiscocks approved these changes

2024-07-04 07:38 UTC, hpritchett-dstl commented on stonesoup/predictor/kernel.py
> +    """AdaptiveKernelKalmanFilter class
would be useful to expand on this docstring to be consistent with documentation for other predictors.

2024-07-04 07:38 UTC, hpritchett-dstl commented on stonesoup/updater/kernel.py
> +    """Adaptive kernel Kalman updater class
would be useful to expand on this docstring to be consistent with documentation for other updaters.

2024-07-04 08:54 UTC, hpritchett-dstl approved these changes

2024-07-04 09:23 UTC, merged