Platform orientation calculated from previous velocity
dstl/Stone-Soup pull request #1090
Opened 2024-10-11 14:30 UTC by nperree-dstl

Slight change to how orientation is calculated for moving platforms. Where the velocity of the platform is small, the orientation is calculated based on the direction it travelled from its previous position. Where the platform has only moved a small distance, and for a non-moving platform the orientation from the previous time step is used.

2024-10-11 14:34 UTC, nperree-dstl commented
Struggling to run tests/docs on my machine so I think this should fix the bug/feature we discussed but I'm not 100% confident...

2024-10-31 01:08 UTC, faultfactory commented
Something that's not clear to me is what happens on first timestep and there is no motion? 
Do we default to ```StateVector([0.0,0.0,0.0])``` or do we instantiate the movable with an orientation to set any attached sensors in the right direction?

2024-11-15 16:12 UTC, akenyon requested changes
I had the same thought as @faultfactory. For a platform with 0 velocity and only one state, `self._property_orientation` would not be assigned a value, which I think would result in an attribute error. We could add a default value or maybe just an error message to explain why orientation couldn't be calculated?

2024-11-15 16:16 UTC, faultfactory commented
> I had the same thought as @faultfactory. For a platform with 0 velocity and only one state, `self._property_orientation` would not be assigned a value, which I think would result in an attribute error. We could add a default value or maybe just an error message to explain why orientation couldn't be calculated?

I think you do both but ideally there wouldn't be an error.  Have a default of zero and then spit something out to the terminal on first use of that value. Then let the processing chain chew on that repeatedly until there's motion.

2025-05-21 09:55 UTC, akenyon approved these changes

2025-05-21 12:03 UTC, sdhiscocks approved these changes

2025-05-21 12:45 UTC, merged