Introduce 2D Obstacles, handling for sensors and the Visibility Informed Bernoulli Filter
dstl/Stone-Soup pull request #1096
Opened 2024-10-23 14:09 UTC by timothy-glover

This pull request introduces a number of new features, focussed around the idea of obstacles in the environment and the impact that this has on blocking sensor line of sight to targets. The contributions are categorised below:

1. `Obstacle` platform. A new base `Platform` type, `Obstacle`, is introduced. The class is designed to allow the user to place obstacles in the environment by specifying the shape of the obstacle as polygon vertices, the position and orientation of the obstacle and any other `Platform` related properties for the obstacle. Moving obstacles should be possible with this implementation but this has not been tested at this stage. `Obstacle` also calculates some properties that are relevant for estimating visibility of targets and does so by caching the property and only recalculating it when necessary (i.e. obstacle position and orientation changes). A `from_obstacle` class method has also been created that allows for creating multiple obstacles that share properties, such as shape data, and redefining others, such as position or orientation.
2. `VisibilityInformed2DSensor` is a new base sensor class that inherits from `SimpleSensor` and is intended to be inherited by 2D sensors (such as those adopting range-bearing and bearing-only sensor models) such that they can call the method `is_visible`, which evaluates the visibility of states by checking whether the line of sight intersects any `Obstacle` edges. This sensor base class allows the user to specify an obstacle list which is used for this purpose, but can be left undefined to resume the original functionality of the sensors before introducing this new base class. `RadarBearing`, `RadarBearingRange`, `RadarRotatingBearing` and `RadarRotatingBearingRange` have all been modified to inherit from this base class and each call `is_visible` from within `is_detectable` meaning that there are no changes to how these sensors are implemented. In order to evaluate the visibility of multiple states at the same time (relevant for the next point), `is_detectable` has been modified to handle arrays of states as well as single states. 
3. `VisibilityInformedBernoulliParticlePredictor` and `VisibilityInformedBernoulliParticleUpdater` have been introduced and modify the `predict_log_weights` and `get_detection_probability` methods of `BernoulliParticlePredictor` and `BernoulliParticleUpdater` respectively. This filter modifies the transition likelihood, birth likelihood and detection probability according to whether particles are inside obstacles or in not visible free space, which prevents the estimated existence from decaying quickly when a target travels behind and `Obstacle` and improves the resulting estimation performance when compared to the original Bernoulli filter.
4. `plot_obstacles` is a method introduced for `Plotterly` and `AnimatedPlotterly` to allow the user to plot lists of, or single, `Obstacle`. The plotting of obstacles assumes that they are closed polygons which are filled accordingly, however, it is possible to specify open obstacles.
5. Tests for each of the above contributions and modifications have also been completed.

2024-10-24 16:15 UTC, timothy-glover commented
Docs appear to have failed due to an exception raised with an unrelated example

2024-10-24 16:26 UTC, jswright-dstl commented on stonesoup/plotter.py
> +    def plot_obstacles(self, obstacles, mapping=[0, 1], obstacle_label='obstacles', **kwargs):
```suggestion
    def plot_obstacles(self, obstacles, mapping=[0, 1], label='obstacles', **kwargs):
```
Formally, I would have suggested `obstacle_label` but due to #1071 `label` is all that is required. The format of labels has changed by removing the prefix to "_label", i.e., `###_label` -> `label`.

2024-10-24 16:26 UTC, jswright-dstl commented on stonesoup/plotter.py
> +        sensor_label: str
```suggestion
        label: str
```

2024-10-24 16:26 UTC, jswright-dstl commented on stonesoup/plotter.py
> +                               name=obstacle_label)
```suggestion
                               name=label)
```

2024-10-24 16:27 UTC, jswright-dstl commented on stonesoup/plotter.py
> +    def plot_obstacles(self, obstacles, mapping=[0, 1], obstacle_label="Obstacles", resize=True,
```suggestion
    def plot_obstacles(self, obstacles, mapping=[0, 1], label="Obstacles", resize=True,
```

2024-10-24 16:27 UTC, jswright-dstl commented on stonesoup/plotter.py
> +        sensor_label: str
```suggestion
        label: str
```

2024-10-24 16:27 UTC, jswright-dstl commented on stonesoup/plotter.py
> +                                   name=obstacle_label)
```suggestion
                                   name=label)
```

2024-10-25 10:51 UTC, hpritchett-dstl commented on stonesoup/sensor/radar/radar.py
> +        return detectable & visible
ah yes, didn't clock it wasn't just comparing Booleans

2025-08-29 11:45 UTC, timothy-glover commented
Docs and tests appear to be failing on unrelated problems. I think the test is failing as this branch is in need of a rebase. 

Summary of changes:
- Removed shape related properties from the `Obstacle` class and created a new `Shape` class which stores this information. This `Shape` class is now an optional property for all platforms and a required property for `Obstacle` specific platforms. This will allow occlusions from other platforms in the environment, not just buildings/obstacles, to influence sensing performance. 
- The new `Shape` class change has been integrated with the rest of the visibility informed code, including sensors, plotting and tests for numerous modules. 
- When calling `measure` on a `VisibilityInformed2DSensor`, the class now checks that any known `Obstacle`s are removed from provided platforms to measure, such that known obstacles are not considered. This functionality may need to change when wanting to detect obstacles along with some consideration on what part of the obstacle is detected.
- Tests have also been improved to cover more `VisibilityInformed2DSensor` functionality.

2025-10-27 14:53 UTC, csherman-dstl commented on stonesoup/platform/shape.py
> +    shape in order for simualted sensors to be affected.
```suggestion
    shape in order for simulated sensors to be affected.
```

2025-10-27 14:53 UTC, csherman-dstl commented on stonesoup/platform/base.py
> +            New property names and associate value for use in newly created obstacle, replacing
```suggestion
            New property names and associated values for use in newly created obstacle, replacing
```

2025-10-27 14:53 UTC, csherman-dstl commented on stonesoup/platform/base.py
> +            name for n, name in enumerate(obstacle._properties) if n < len(args)}
I believe the arguments produced in this function are different to those read in the __init__ function.

e.g. `Obstace.from_obstacle(obstacle, State([0, 0]), [0, 1])` raises the error `TypeError: multiple values for argument 'position_mapping'`

2025-10-27 14:53 UTC, csherman-dstl commented on stonesoup/plotter.py
> +            artists.append(self.ax.scatter(*obstacle.vertices, **obstacle_kwargs))
This method is giving a `Value Error: Supply a 'c' argument or a 'color' kwarg but not both`
I believe that using `*obstacle.vertices` gives four different arguments (for an obstacle with four corners) instead of the 2 for x and y.

```suggestion
            artists.append(self.ax.scatter(*obstacle.vertices.T, **obstacle_kwargs))
```
or a copy from the plotterly implementation
```suggestion
            obstacle_xy = obstacle.vertices[mapping, :]
            artists.append(self.ax.scatter(x=obstacle_xy[0, :],
                                           obstacle_xy[1, :], **obstacle_kwargs))

2025-10-27 14:53 UTC, csherman-dstl commented on stonesoup/plotter.py
> +    def plot_obstacles(self, obstacles, mapping=[0, 1], label='Obstacles', **kwargs):
I don't believe mapping is used (although vertices already accounts for the obstacles mapping values)

2025-10-27 14:53 UTC, csherman-dstl commented on stonesoup/sensor/sensor.py
> +    shapely = True
```suggestion
    has_shapely = True
```
Does it make sense to define this const as something different to the name of the module for readability?

2025-10-27 14:53 UTC, csherman-dstl commented on stonesoup/sensor/sensor.py
> +        if isinstance(self, VisibilityInformed2DSensor) and self.obstacles:
```suggestion
        if self.obstacles:
```
Is this condition not guaranteed to be True?

2025-10-27 14:53 UTC, csherman-dstl commented on stonesoup/sensor/sensor.py
> +                                     state.state_vector[self.position_mapping[0:2], :]])]
```suggestion
            elif isinstance(state, ParticleState):
                position_concat = np.tile(self.position, [nstates])
                line_segments = \
                    MultiLineString(
                        [*np.array([position_concat,
                                    state.state_vector[self.position_mapping[0:2], :]])
                         .transpose(2, 0, 1)]).geoms
            else:
                nstates = 1
                line_segments = \
                    [LineString([self.position[0:2],
                                 state.state_vector[self.position_mapping[0:2], :]])]
```

2025-10-27 14:53 UTC, csherman-dstl commented on stonesoup/sensor/sensor.py
> +                    point_sequence = [Point(state.state_vector[self.position_mapping[0:2], :].T)]
```suggestion
            elif isinstance(state, ParticleState):
                point_sequence = \
                    MultiPoint(state.state_vector[self.position_mapping[0:2], :].T).geoms
            else:
                point_sequence = [Point(state.state_vector[self.position_mapping[0:2], :].T)]
```

2025-10-27 14:53 UTC, csherman-dstl commented on stonesoup/sensor/sensor.py
> +            intersections[n, :] = (alpha >= 0) & (alpha <= 1) & (beta >= 0) & (beta <= 1)
which one?

2025-10-31 15:37 UTC, timothy-glover commented on stonesoup/platform/base.py
> +            name for n, name in enumerate(obstacle._properties) if n < len(args)}
Solved this by removing the possibility of providing `args` to `from_obstacle`

2025-11-04 09:56 UTC, sdhiscocks requested changes

2025-11-04 09:56 UTC, sdhiscocks commented on stonesoup/platform/shape.py
> +        "to its centroid without any orientation. Defaults to `None`")
```suggestion
    shape_data: StateVectors = Property(
        doc="Coordinates defining the vertices of the obstacle relative"
        "to its centroid without any orientation.")
```

2025-11-04 09:56 UTC, sdhiscocks commented on stonesoup/plotter.py
> +            obstacle's position. Default is [0, 1].
```suggestion
```

2025-11-04 09:56 UTC, sdhiscocks commented on stonesoup/plotter.py
> +            obstacle's position. Default is [0, 1].
```suggestion
```

2025-11-04 09:56 UTC, sdhiscocks commented on stonesoup/plotter.py
> +            obstacle's position. Default is [0, 1].
```suggestion
```

2025-11-04 09:56 UTC, sdhiscocks commented on stonesoup/predictor/particle.py
> +        default=None, doc="Collection of sensors providing measurements for update stages. "
Need to initialise this as empty list/set, but recent change with #1232 could deal with this and added on merge.

2025-11-04 09:56 UTC, sdhiscocks commented on stonesoup/predictor/particle.py
> +
```suggestion
class VisibilityInformedBernoulliParticlePredictor(BernoulliParticlePredictor):
    """Visibility informed Bernoulli Particle Predictor class

```

2025-11-04 09:56 UTC, sdhiscocks commented on stonesoup/plotter.py
> +    def plot_obstacles(self, obstacles, mapping, label="Obstacles", **kwargs):
```suggestion
    def plot_obstacles(self, obstacles, label="Obstacles", **kwargs):
```

2025-11-04 09:56 UTC, sdhiscocks commented on stonesoup/plotter.py
> +    def plot_obstacles(self, obstacles, mapping=[0, 1], label='Obstacles', **kwargs):
```suggestion
    def plot_obstacles(self, obstacles, label='Obstacles', **kwargs):
```

2025-11-04 09:56 UTC, sdhiscocks commented on stonesoup/plotter.py
> +    def plot_obstacles(self, obstacles, mapping=[0, 1], label='Obstacles', **kwargs):
```suggestion
    def plot_obstacles(self, obstacles, label='Obstacles', **kwargs):
```

2025-11-04 09:56 UTC, sdhiscocks commented on stonesoup/sensor/sensor.py
> +            return self._obstacle_tree
```suggestion
    @property
    def _obstacle_tree(self):
        if self.moving_obstacle_flag:
            return STRtree([Polygon(obstacle.vertices.T) for obstacle in self.obstacles])
        else:
            return self._cached_obstacle_tree
```

2025-11-04 09:56 UTC, sdhiscocks commented on stonesoup/sensor/sensor.py
> +            obstacle_tree = self.get_obstacle_tree()
```suggestion
            obstacle_tree = self._obstacle_tree
```

2025-11-04 09:56 UTC, sdhiscocks commented on stonesoup/sensor/sensor.py
> +            obstacle_tree = self.get_obstacle_tree()
```suggestion
            obstacle_tree = self._obstacle_tree
```

2025-11-04 09:56 UTC, sdhiscocks commented on stonesoup/sensor/sensor.py
> +            self._all_rel_edges = []
```suggestion
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        
        if self.obstacles is None:
            self.obstacles = set()

        self._str_tree_is_visible_trigger = has_shapely and len(self.obstacles) > 100
        self._cached_obstacle_tree = None

        self._relevant_obs = []
        self._relevant_obs_idx = []

        self._all_verts = [obstacle.vertices for obstacle in self.obstacles]
        self._all_rel_edges = [obstacle.relative_edges for obstacle in self.obstacles]
```

2025-11-04 09:56 UTC, sdhiscocks commented on stonesoup/updater/particle.py
> +            log_detection_probability = self.get_detection_probability(prediction)
```suggestion
            log_detection_probability = self.get_log_detection_probability(prediction)
```

2025-11-04 09:56 UTC, sdhiscocks commented on stonesoup/updater/particle.py
> +    def get_detection_probability(self, prediction):
```suggestion
    def get_log_detection_probability(self, prediction):
```

2025-11-04 09:56 UTC, sdhiscocks commented on stonesoup/updater/particle.py
> +    def get_detection_probability(self, prediction):
```suggestion
    def get_log_detection_probability(self, prediction):
```

2025-11-13 14:35 UTC, sdhiscocks approved these changes

2025-11-17 08:37 UTC, csherman-dstl approved these changes

2025-11-17 08:37 UTC, csherman-dstl commented on stonesoup/platform/shape.py
> +                                     -1).astype(int)
```suggestion
            self.simplices = np.roll(np.arange(self.shape_data.shape[1]), -1)
```

Does this do the same thing

2025-11-17 08:37 UTC, csherman-dstl commented on stonesoup/sensor/sensor.py
> +            in_obstacles = sum(intersections, 0) % 2 != 0
Found a weird edge case where the line between the sensor and the target goes directly through the vertex causing this to return the wrong value.
(similarly if the sensor happens to be within an obstacle all results are inverted but that is less relevant)

2025-11-17 12:43 UTC, merged