Add Additional SIAPs
dstl/Stone-Soup pull request #321
Opened 2020-10-30 11:57 UTC by oharrald-Dstl

Adds: PA (positional accuracy), VA (velocity accuracy), num_tracks (no. tracks), num_truths (no. ground truth paths),
and single-time: A, S, PA, VA (C already implemented) generators.

Addresses issue #257 'Add additional SIAP Metrics'.

2020-11-02 16:05 UTC, jswright-dstl approved these changes

2020-11-16 15:31 UTC, sdhiscocks requested changes

2020-11-16 15:38 UTC, sdhiscocks commented
Should have noted, that once #328 is merged, it would be good to resolve the issue with identity based metrics, that currently limits metrics being based on final track identity.

2020-11-16 17:09 UTC, sdhiscocks approved these changes

2020-11-16 17:12 UTC, merged