Fix plotter metric so it uses Stone Soup Plotter class
dstl/Stone-Soup pull request #382
Opened 2021-02-19 16:11 UTC by nperree-dstl

Change how plotter metric works so it uses the Stone Soup plotting functions from the Plotter class

2021-02-22 12:18 UTC, svidal-dstl approved these changes

2021-02-22 17:04 UTC, jswright-dstl approved these changes

2021-02-24 16:09 UTC, sdhiscocks requested changes

2021-02-24 16:09 UTC, sdhiscocks commented on stonesoup/metricgenerator/plotter.py
> +                                     detections, uncertainty=False, particle=False):
So `uncertainty` and `particle` should be `Property`s on the class as well, passed when calling this method from `TwoDPlotter.compute_metric()`.

2021-02-24 17:11 UTC, sdhiscocks approved these changes

2021-02-24 17:12 UTC, merged