Information filter
dstl/Stone-Soup pull request #467
Opened 2021-07-23 15:38 UTC by jmbarr

The information form of the Kalman filter predictor and updater classes. Could be extended to encompass other members of the Kalman (EKF, UKF, etc) family.

2021-07-26 07:31 UTC, sdhiscocks requested changes
A f ew changes required to match up with existing Kalman filter and type hints, but otherwise looks good :+1:

2021-07-26 07:31 UTC, sdhiscocks commented on stonesoup/predictor/information.py
> +    @lru_cache()
Should use `predict_lru_cache` from `._utils` here.

2021-07-26 07:31 UTC, sdhiscocks commented on .idea/codeStyles/codeStyleConfig.xml
> +</component>
This file should be removed.

2021-07-26 07:31 UTC, sdhiscocks commented on stonesoup/predictor/information.py
> +            inv_transition_matrix = self.transition_model.inverse_matrix(**kwargs)
```suggestion
        if hasattr(self.transition_model, 'inverse_matrix'):
            inv_transition_matrix = self.transition_model.inverse_matrix(**kwargs)
```

2021-07-26 07:31 UTC, sdhiscocks commented on stonesoup/predictor/information.py
> +            "will create a zero-effect linear :class:`~.ControlModel`.")
```suggestion
    transition_model: LinearGaussianTransitionModel = Property(
        doc="The transition model to be used.")
    control_model: LinearControlModel = Property(
        default=None,
        doc="The control model to be used. Default `None` where the predictor "
            "will create a zero-effect linear :class:`~.ControlModel`.")
```

2021-07-26 07:31 UTC, sdhiscocks commented on stonesoup/updater/information.py
> +            "will be thrown.")
```suggestion
    measurement_model: LinearGaussian = Property(
        default=None,
        doc="A linear Gaussian measurement model. This need not be defined if "
            "a measurement model is provided in the measurement. If no model "
            "specified on construction, or in the measurement, then error "
            "will be thrown.")
```

2021-07-26 07:31 UTC, sdhiscocks commented on stonesoup/types/state.py
> +    precision = Property(PrecisionMatrix, doc='precision matrix of state.')
```suggestion
    precision: PrecisionMatrix = Property(doc='precision matrix of state.')
```

2021-07-26 07:31 UTC, sdhiscocks commented on stonesoup/updater/information.py
> +    Analogously with the :class:`~.InformationStatePredictor`, the measurement model is queried for
```suggestion
    Analogously with the :class:`~.InformationKalmanPredictor`, the measurement model is queried for
```

2021-07-26 07:31 UTC, sdhiscocks commented on stonesoup/updater/information.py
> +            posterior_precision = (posterior_precision + posterior_precision.T)/2
```suggestion
        if self.force_symmetric_covariance:
            posterior_precision = (posterior_precision + posterior_precision.T)/2
```

2021-07-26 07:31 UTC, sdhiscocks commented on stonesoup/updater/information.py
> +            Default is `False`
```suggestion
    def update(self, hypothesis, **kwargs):
        r"""The Information filter update (corrector) method. Given a hypothesised association
        between a predicted information state and an actual measurement, calculate the posterior
        information state.

        Parameters
        ----------
        hypothesis : :class:`~.SingleHypothesis`
            the prediction-measurement association hypothesis. This hypothesis
            carries a predicted information state.
```

2021-07-30 08:16 UTC, nperree-dstl approved these changes
Found one link that didn't work, otherwise it looks good and all makes sense!

2021-07-30 08:16 UTC, nperree-dstl commented on stonesoup/updater/information.py
> +        : :class:`GaussianMeasurementPrediction`
```suggestion
        : :class:`~.GaussianMeasurementPrediction`
```

2021-08-09 09:03 UTC, sdhiscocks approved these changes

2021-08-09 15:21 UTC, merged