Add OpenSky demo
dstl/Stone-Soup pull request #488
Opened 2021-08-20 12:02 UTC by hpritchett-dstl

Add demonstration of a Stone Soup multi-target tracker applied to ADS-B data taken from The OpenSky Network.

2021-09-03 10:30 UTC, sdhiscocks commented on docs/demos/OpenSky_Demo.py
> +    duration='PT0S')).add_to(m)
```suggestion
TimestampedGeoJson(
    data=geo_json,
    transition_time=200,
    auto_play=True,
    add_last_point=False,
    period='PT10S',
    duration='PT0S').add_to(m)
```

2021-09-13 14:27 UTC, nperree-dstl approved these changes
Just a couple of formatting points to make it read nicer and a fix for a broken link. Otherwise looks really good!

2021-09-13 14:27 UTC, nperree-dstl commented on docs/demos/OpenSky_Demo.py
> +# By having delete_last_pred = True, the state that caused a track to be deleted will be deleted
```suggestion
# By having `delete_last_pred = True`, the state that caused a track to be deleted will be deleted
```

2021-09-13 14:27 UTC, nperree-dstl commented on docs/demos/OpenSky_Demo.py
> +# The variable trail_Size will determine how much history of the track we want to be seen.
```suggestion
# The variable `trail_Size` will determine how much history of the track we want to be seen.
```

2021-09-13 14:27 UTC, nperree-dstl commented on docs/demos/OpenSky_Demo.py
> +# We will plot a LineString to display our track, taking into account our specified trail_Size
```suggestion
# We will plot a LineString to display our track, taking into account our specified `trail_Size`
```

2021-09-30 10:48 UTC, sdhiscocks requested changes
Looks good. The only thing is the transition model noise parameters look very large. I think this is an issue with the initial prior for velocity being too small. Suggested patch below, that increases the prior uncertainty, which then means model uncertainty can be reduced to much lower values.

```patch
diff --git a/docs/demos/OpenSky_Demo.py b/docs/demos/OpenSky_Demo.py
index d1aee11d..e23558aa 100644
--- a/docs/demos/OpenSky_Demo.py
+++ b/docs/demos/OpenSky_Demo.py
@@ -182,9 +182,9 @@ detection_sim = PlatformDetectionSimulator(groundtruth, platforms)
 # (if it is a prediction).
 
 transition_model = CombinedLinearGaussianTransitionModel(
-    (ConstantVelocity(1500), ConstantVelocity(1500), ConstantVelocity(1000)))
+    (ConstantVelocity(20), ConstantVelocity(20), ConstantVelocity(2)))
 init_transition_model = CombinedLinearGaussianTransitionModel(
-    (ConstantVelocity(8500), ConstantVelocity(8500), ConstantVelocity(1000)))
+    (ConstantVelocity(5), ConstantVelocity(5), ConstantVelocity(2)))
 
 from stonesoup.predictor.kalman import ExtendedKalmanPredictor
 predictor = ExtendedKalmanPredictor(transition_model)
@@ -195,7 +195,7 @@ updater = ExtendedKalmanUpdater(measurement_model=None)
 
 from stonesoup.hypothesiser.distance import DistanceHypothesiser
 from stonesoup.measures import Mahalanobis
-hypothesiser = DistanceHypothesiser(predictor, updater, Mahalanobis(), missed_distance=3)
+hypothesiser = DistanceHypothesiser(predictor, updater, Mahalanobis(), missed_distance=5)
 
 from stonesoup.dataassociator.neighbour import GNNWith2DAssignment
 data_associator = GNNWith2DAssignment(hypothesiser)
@@ -216,11 +216,11 @@ from stonesoup.types.state import GaussianState
 initiator = MultiMeasurementInitiator(
     GaussianState(
         np.array([[0], [0], [0], [0], [0], [0]]),   # Prior State
-        np.diag([8000, 90, 8000, 90, 0, 20])),
+        np.diag([15**2, 100**2, 15**2, 100**2, 15**2, 20**2])),
     measurement_model=None,
     deleter=deleter,
     data_associator=GNNWith2DAssignment(
-        DistanceHypothesiser(init_predictor, updater, Mahalanobis(), missed_distance=1.8)),
+        DistanceHypothesiser(init_predictor, updater, Mahalanobis(), missed_distance=3)),
     updater=updater,
     min_points=2
     )

```

2021-09-30 14:46 UTC, sdhiscocks approved these changes

2021-09-30 14:50 UTC, merged