Fix bug with pre-fetching noise in cases of only a single target
dstl/Stone-Soup pull request #724
Opened 2022-09-23 13:07 UTC by sdhiscocks

2022-09-23 13:15 UTC, jswright-dstl approved these changes

2022-09-23 17:16 UTC, gawebb-dstl requested changes
In the scenario `len(ground_truths) == 1 and noise == True` (which happens in the Disjoint_Tracking_Classification.py example) 
Then `measurement_noise = True`
Which doesn't cause an error on the line `measurement_vector += measurement_noise` 
It just adds 1 to the `measurement_vector` 

Would this be a suitable solution:
```
if noise is True:
    # Pre-fetch noise values when more than one target
    if len(ground_truths) > 1:
        noise_vectors_iter = iter(measurement_model.rvs(len(ground_truths), **kwargs))
    else:
        noise_vectors_iter = iter([measurement_model.rvs(**kwargs)])
```

2022-09-26 09:25 UTC, sdhiscocks commented
> In the scenario `len(ground_truths) == 1 and noise == True` (which happens in the Disjoint_Tracking_Classification.py example) Then `measurement_noise = True` Which doesn't cause an error on the line `measurement_vector += measurement_noise` It just adds 1 to the `measurement_vector`
> 
> Would this be a suitable solution:
> 
> ```
> if noise is True:
>     # Pre-fetch noise values when more than one target
>     if len(ground_truths) > 1:
>         noise_vectors_iter = iter(measurement_model.rvs(len(ground_truths), **kwargs))
>     else:
>         noise_vectors_iter = iter([measurement_model.rvs(**kwargs)])
> ```

Thanks @gawebb-dstl, I hadn't spotted that. I've updated it for sensors where this is an issue.

2022-10-04 13:21 UTC, gawebb-dstl commented
@sdhiscocks I noticed you were having to rewrite the same code in many different places, so I tried to abstract that code to one class see #732

2022-10-10 12:50 UTC, merged