Add average uncertainty method to UncertaintyRewardFunction
dstl/Stone-Soup pull request #746
Opened 2022-11-09 16:17 UTC by mharris-dstl

2022-11-11 13:06 UTC, sdhiscocks requested changes

2022-11-11 13:06 UTC, sdhiscocks commented on stonesoup/sensormanager/reward.py
> +    method: str = Property(default="sum", doc="Determines the type of uncertainty reward - use 'sum' or 'average'.")
Should probably avoid a "magic string" here:

- One option is to have an [`enum`](https://docs.python.org/3/library/enum.html);
- another is to have Boolean option of `average` instead, defaulting to `False`; 
- or maybe have this as a `Callable` defaulting to `np.sum`, but suggest `np.average` as an alternative in doc string (leaves option there other functions that then could be used e.g. `np.median` or custom lambda function).

2022-11-11 13:06 UTC, sdhiscocks commented on stonesoup/sensormanager/reward.py
> +    method: str = Property(default="sum", doc="Determines the type of uncertainty reward - use 'sum' or 'average'.")
This line is too long also, failing *flake8* tests.

2022-12-01 11:47 UTC, nperree-dstl approved these changes

2023-01-30 10:01 UTC, sdhiscocks approved these changes

2023-01-30 10:02 UTC, sdhiscocks requested changes
Could you add a test to cover `method_sum` is `True`.

2023-02-08 09:46 UTC, closed without merging