Add track stitching class and example.
dstl/Stone-Soup pull request #764
Opened 2023-01-23 12:43 UTC by spike-dstl

Co-authored-by: Scott Florence <sflorence@dstl.gov.uk>

Pull request to add track stitching example and 'Stitcher' class to main stone soup repository.

2023-01-30 09:57 UTC, sdhiscocks commented
Code coverage could be improved. It looks like the *backwards* methods aren't tested currently.

2023-02-13 16:04 UTC, sdhiscocks requested changes

2023-02-13 16:04 UTC, sdhiscocks commented on stonesoup/tests/test_stitcher.py
> +np.random.seed(100)
Can't really use seed in test (without resetting it again). Probably best to use seed in models, and also capture example starting points from this seed for now.

2023-02-13 16:04 UTC, sdhiscocks commented on docs/examples/Track_Stitcher_Example.py
> +_ = SIAPTableGenerator(siap_averages).compute_metric()
Would be good to compare before and after, but I can see issue is that stitched tracks aren't interpolated. Probably should add that as separate component that could be used.

2023-02-13 16:04 UTC, sdhiscocks commented on stonesoup/stitcher.py
> +from scipy.optimize import linear_sum_assignment
```suggestion
from collections import defaultdict
from copy import deepcopy
from datetime import timedelta

from scipy.optimize import linear_sum_assignment

from .base import Base, Property
from .hypothesiser import Hypothesiser
from .models.measurement.linear import LinearGaussian
from .types.detection import Detection
from .types.track import Track
```

2023-02-13 16:04 UTC, sdhiscocks commented on docs/examples/Track_Stitcher_Example.py
> +        return tracks
Replace with just importing the new class.

2023-02-27 07:57 UTC, sdhiscocks commented on stonesoup/tests/test_stitcher.py
> +    return historic_tracks
Could just use the standard `MultiTargetTracker`

2023-05-15 07:59 UTC, spike-dstl commented
> Code coverage could be improved. It looks like the _backwards_ methods aren't tested currently.

2023-05-15 08:22 UTC, spike-dstl commented on stonesoup/stitcher.py
> +        state = track[0] if not backward else track[-1]
This gives a different result than wanted: 
The original method gives: 
backward = False -> state = track[0]
backward = True -> state = track[-1]

The new method would give: 
backward = False -> state = track[-1]
backward = True -> state = track[0]

I think your point is correct though, and the below change should be correct?
```suggestion
    def _extract_detection(track, backward=False):
        state = track[-1] if not backward else track[0]
```

2023-05-16 09:58 UTC, sdhiscocks approved these changes

2023-05-16 12:13 UTC, merged