Kafka readers and writers
dstl/Stone-Soup pull request #799
Opened 2023-05-03 15:52 UTC by sglvladi

This PR contributes the following classes:
- `KafkaDetectionReader`: A detection reader that reads detections from a Kafka broker
- `KafkaGroundTruthReader`: A ground truth reader that reads ground truths from a Kafka broker
- `KafkaWriter`: A simple Kafka writer that writes data to a Kafka topic.

2023-06-05 09:17 UTC, jswright-dstl approved these changes

2023-06-05 09:38 UTC, sdhiscocks requested changes
Looks good, but I think `confluent_kafka` should be optional.

Future aspiration would be to use JSON Path syntax to allow selection of fields, which would enable this to be used more easily with GeoJSON for example.

2023-06-05 09:38 UTC, sdhiscocks commented on setup.cfg
> +    confluent-kafka
I think this should be optional extra.

2023-06-05 09:38 UTC, sdhiscocks commented on stonesoup/reader/kafka.py
> +from stonesoup.base import Property
```suggestion
from dateutil.parser import parse

from stonesoup.base import Property
```

2023-06-05 09:38 UTC, sdhiscocks commented on stonesoup/writer/kafka.py
> +from stonesoup.base import Property
```suggestion
from confluent_kafka import Producer

from stonesoup.base import Property
```

2023-08-08 20:21 UTC, jswright-dstl approved these changes

2023-08-09 15:45 UTC, merged