Add GaussianMixtureInitiator, ASDGaussianInitiator and EnsembleInitiator
dstl/Stone-Soup pull request #873
Opened 2023-10-06 09:13 UTC by csherman-dstl

Add initiators for GaussianMixture, ASDGaussian and Ensemble state with accompanying tests

2023-10-06 10:08 UTC, csherman-dstl commented
needed to rebase from main

2023-10-17 10:44 UTC, sdhiscocks requested changes

2023-10-17 10:44 UTC, sdhiscocks commented on stonesoup/initiator/simple.py
> +        doc="Starting timestep attributed to the prior state.")
This really shouldn't be required. Can the timestamps be set to list of `None` or I guess list just containing `self.initiator.prior_state.timestamp` like other parameters.

2023-10-17 10:44 UTC, sdhiscocks commented on stonesoup/initiator/simple.py
> +                max_nstep=0,
I think this should be a parameter defined on the initiator (like `ensemble_size` below).

2023-10-17 10:44 UTC, sdhiscocks commented on stonesoup/initiator/simple.py
> +
Would it be possible to use `EnsembleStateUpdate.from_gaussian_state()` and remove the `create_ensemble` method in the initiator? May need to modify the `from_gaussian_state()` to accept kwargs in order to pass the hypothesis.

2023-10-25 10:14 UTC, sdhiscocks approved these changes

2023-10-30 21:43 UTC, jswright-dstl approved these changes

2023-10-31 09:19 UTC, merged