Example of Ensemble Kalman filter with Out-Of-Sequence measurements
dstl/Stone-Soup pull request #915
Opened 2023-12-22 14:03 UTC by A-acuto

This PR adds a simple example of using a Kalman Filter with measurements with a fixed delay from a sensor.

2024-02-19 11:27 UTC, spike-dstl requested changes
Grammatical suggestions to support email sent 19/02/2024.

2024-02-20 14:58 UTC, spike-dstl approved these changes
One final spelling mistake correction. Approving with assumption that this will be fixed.

2024-02-20 14:58 UTC, spike-dstl commented on docs/examples/KalmanFilterOOSMExample.py
> +# filters, my making the assumption that the delay of the delayed measurements is known, and constant.
```suggestion
# filters, by making the assumption that the delay of the delayed measurements is known, and constant.
```

2024-03-01 09:29 UTC, nperree-dstl approved these changes
Only a minor suggestion, otherwise looks good!

2024-03-01 09:29 UTC, nperree-dstl commented on docs/examples/KalmanFilterOOSMExample.py
> +# uncertain timesteps.
```suggestion
# In the literature, there are examples on how to deal with such time-delays and
# uncertain timesteps [#]_.
```

2024-03-19 10:30 UTC, merged