Make format of Video Processing demo variables consistent, and fix typo
dstl/Stone-Soup pull request #953
Opened 2024-02-07 16:51 UTC by orosoman-dstl

Just me being picky about spelling/consistency

2024-02-15 14:43 UTC, sdhiscocks commented
You'll also need to updated ipynb and RST file, and update MD5 hash, in order for docs to build correctly. See #635 for example PR that's done this before.

2024-02-20 10:17 UTC, mharris-dstl requested changes
Apologies, didn't see above comments.

2024-02-21 12:50 UTC, orosoman-dstl commented
Hopefully now fixed. Some weird things have happened with the ipynb diff though, hopefully not important.

2024-03-26 16:03 UTC, mharris-dstl approved these changes

2025-05-20 09:06 UTC, closed without merging